package com.example.base_project.select.util

object SelectConstants {
    const val AUDIO = "AUDIO"
    const val AUDIO_LIST = "AUDIO_LIST"
    const val AUDIO_SELECTED_FRAGMENT = "AUDIO_SELECTED_FRAGMENT"
    const val EXTENSION_AUDIO_AAC = "aac"
    const val EXTENSION_AUDIO_AMR = "amr"
    const val EXTENSION_AUDIO_M4A = "m4a"
    const val EXTENSION_AUDIO_MP3 = "mp3"
    const val EXTENSION_AUDIO_WAV: String = "wav"
    const val EXTENSION_VIDEO_3GP: String = "3gp"
    const val EXTENSION_VIDEO_AVI: String = "avi"
    const val EXTENSION_VIDEO_FLV: String = "flv"
    const val EXTENSION_VIDEO_MKV: String = "mkv"
    const val EXTENSION_VIDEO_MOV: String = "mov"
    const val EXTENSION_VIDEO_MP4: String = "mp4"
    const val EXTENSION_VIDEO_OGG: String = "ogg"
    const val EXTENSION_VIDEO_RMVB: String = "rmvb"
    const val EXTENSION_VIDEO_WMV: String = "wmv"
    const val FILE_BROWSER_FRAGMENT: String = "FILE_BROWSER_FRAGMENT"
    const val FROM: String = "FROM"
    const val FROM_AUDIO_CONVERTER: Int = 10004
    const val FROM_AUDIO_CONVERTER_FOR_ADD: Int = 20004
    const val FROM_COMPRESS_AUDIO: Int = 10007
    const val FROM_COMPRESS_AUDIO_FOR_ADD: Int = 20007
    const val FROM_DEFAULT: Int = 10001
    const val FROM_MERGE_AUDIO: Int = 10003
    const val FROM_MERGE_AUDIO_FOR_ADD: Int = 20003
    const val FROM_MIX_AUDIO: Int = 10006
    const val FROM_MIX_AUDIO_FOR_ADD: Int = 20006
    const val FROM_MUTE_PART: Int = 10013
    const val FROM_MUTE_PART_FOR_ADD: Int = 20013
    const val FROM_REMOVE_PART: Int = 10012
    const val FROM_REMOVE_PART_FOR_ADD: Int = 20012
    const val FROM_REVERSE_AUDIO: Int = 10010
    const val FROM_REVERSE_AUDIO_FOR_ADD: Int = 20010
    const val FROM_SPEED_EDITOR: Int = 10011
    const val FROM_SPEED_EDITOR_FOR_ADD: Int = 20011
    const val FROM_SPLIT_AUDIO: Int = 10009
    const val FROM_SPLIT_AUDIO_FOR_ADD: Int = 20009
    const val FROM_TAG_EDITOR: Int = 10008
    const val FROM_TAG_EDITOR_FOR_ADD: Int = 20008
    const val FROM_TRIM_ADVANCED_AUDIO_FOR_ADD: Int = 20002
    const val FROM_TRIM_AUDIO: Int = 10002
    const val FROM_All_AUDIO: Int = 10015
    const val FROM_TRIM_AUDIO_FOR_ADD: Int = 20001
    const val FROM_VIDEO_TO_AUDIO: Int = 10005
    const val FROM_VIDEO_TO_AUDIO_FOR_ADD: Int = 20005
    const val FROM_VOLUME_BOOSTER: Int = 10014
    const val FROM_VOLUME_BOOSTER_FOR_ADD: Int = 20014
    const val MIME_TYPE_AUDIO_3GPP: String = "audio/3gpp"
    const val MIME_TYPE_AUDIO_AAC: String = "audio/aac"
    const val MIME_TYPE_AUDIO_AMR: String = "audio/amr"
    const val MIME_TYPE_AUDIO_M4A: String = "audio/mp4"
    const val MIME_TYPE_AUDIO_MP3: String = "audio/mpeg"
    const val MIME_TYPE_AUDIO_WAV: String = "audio/x-wav"
    const val MIME_TYPE_VIDEO: String = "video/*"
    const val PLAY_STATE_NORMAL: Int = 1
    const val PLAY_STATE_PLAYING: Int = 2
    const val VIDEO: String = "VIDEO"
    const val VIDEO_LIST_VIEW_TYPE_AD: Int = 1
    const val VIDEO_LIST_VIEW_TYPE_COUNT: Int = 2
    const val VIDEO_LIST_VIEW_TYPE_VIDEO: Int = 0
}